[package]
name = "minicbor-embedded-io"
version = "0.1.0"
edition = "2021"

[dependencies]
embedded-io = { version = "0.4", features = ["async"] }
minicbor = "0.19"

[dev-dependencies]
tokio = { version = "1", features = ["macros", "rt"] }